// handleLogin
// handleLogout
// handleRegister
// handleUpdateProfile
// handleDeleteAccount
// handleForgotPassword
// handleResetPassword
// handleGetProfile
// handleGetUsers
// handleGoogleLogin
